config/routes.rb
Rails.application.routes.draw do
  resources :memberships do 
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users do 
    post 'toggle_frozen_status', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :places, only:[:index, :show]

  resources :styles

  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  root 'breweries#index'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :beer_club
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @membership = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @beer_clubs = BeerClub.all

  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user_id = current_user.id
    bc = BeerClub.find_by id:@membership.beer_club_id

    if bc.members.include? current_user
      redirect_to beer_clubs_path, notice: "You can only join the same Beer club once!"
    else
      respond_to do |format|
        if @membership.save
          format.html { redirect_to beer_club_path(bc.id), notice: "Your application to join, #{bc.name} has been accepted. You have to wait for an accepted memeber to confirm your membership" }
          format.json { render :show, status: :created, location: @membership }
        else
          format.html { render :new }
          format.json { render json: @membership.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'Membership was successfully ended.' }
      format.json { head :no_content }
    end
  end
  def confirm
   membership = Membership.find(params[:id])
   membership.update_attribute :confirmed, (true)
   redirect_to :back
   #redirect_to :back, notice:"#{brewery.name} activity status changed to #{new_status}"
 end


 private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:user_id, :beer_club_id, :confirmed)
    end
  end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
   <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |

app/views/memberships/index.html.erb
<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Beer club</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user_id %></td>
        <td><%= membership.beer_club_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>
<%= render 'form' %>

app/views/memberships/show.html.erb
<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<p>
  <strong>Beer club:</strong>
  <%= @membership.beer_club_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |