config/routes.rb
Rails.application.routes.draw do
  resources :memberships do 
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users do 
    post 'toggle_frozen_status', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :places, only:[:index, :show]

  resources :styles

  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  root 'breweries#index'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
	has_many :memberships
	has_many :members, through: :memberships , source: :user

	has_many :confirmed_memberships, -> {where confirmed:true}, class_name: "Membership"
	has_many :unconfirmed_memberships, -> {where confirmed:[false, nil]}, class_name: "Membership"


	has_many :confirmed_members, through: :confirmed_memberships, source: :user
	has_many :unconfirmed_members, through: :unconfirmed_memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :is_admin, only: [:destroy]
  before_action :is_admin, only: [:destroy]



  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @confirmed_members= @beer_club.confirmed_members
    @unconfirmed_members= @beer_club.unconfirmed_members

    unless current_user.nil?
      @membership = Membership.find_by user_id:current_user.id, beer_club_id:params[:id]
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    respond_to do |format|
      if @beer_club.save
        Membership.create user_id:current_user.id, beer_club_id:@beer_club.id, confirmed:true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
  end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %>

app/views/beer_clubs/index.html.erb
<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club , class:"btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) , class:"btn btn-primary"%></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path , class:"btn btn-success" %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

app/views/beer_clubs/show.html.erb
<h1><%= @beer_club.name %></h1>

<p>
	<%= "Founded #{@beer_club.founded} in #{@beer_club.city}" %>
</p>


<h2>Members</h2>
<% @confirmed_members.each do |member| %>
<ul>
	<li><%= link_to member.username, user_path(member.id) %> </li>
</ul>
<% end %>
<% if current_user && is_member %>
<h2>Outstanding applications</h2> 
<% @unconfirmed_members.each do |member| %>
<ul>
	<li><%= link_to member.username, user_path(member.id) %> 
		<%= link_to "Confirm", 
		confirm_membership_path(member.membership_of_beer_club(@beer_club.id).id), 
		method: :post, class: "btn btn-primary" %>
	</li>

</ul>
<% end %>
<% end %>


</br>
</br>
</br>
<% if current_user && is_member %>
<%= form_for(@membership, method: "delete") do |f| %>
<%= f.hidden_field :beer_club_id %>
<%= f.submit value: "End your membership" %>
<% end %>
<% end %>
<%= link_to 'Edit', edit_beer_club_path(@beer_club) %> |
<%= link_to 'Delete', @beer_club, method: :delete, data: { confirm: "Are you sure you want to delete \'#{@beer_club.name}\'" }%>