config/routes.rb
Rails.application.routes.draw do
  resources :memberships do 
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users do 
    post 'toggle_frozen_status', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :places, only:[:index, :show]

  resources :styles

  post 'places', to:'places#search'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  root 'breweries#index'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	include RatingAverage

	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers

	scope :active, -> {where active:true}
	scope :retired, ->{where active:[nil,false]}

	validates :name, presence: true
	validates :year, numericality: 
	{ greater_than_or_equal_to: 1042, 
		only_integer: true}
		validate :year_can_not_be_later_than_current_date

		def year_can_not_be_later_than_current_date
			if year > Time.now.year
				errors.add(:year, ":You cannot establish a brewery in the future if you're not Marty McFly")
			end
		end
		def print_report
			puts name
			puts "established at year #{year}"
			puts "number of beers #{beers.count}"
		end
		def restart
			self.year = 2015
			puts "changed year to #{year}"
		end
		def self.top(n)
			sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating||0) }
			sorted_by_rating_in_desc_order[0..n-1]
		end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :nglist]
  before_action :is_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]
  before_action :expire_cache_fragments, only: [:update, :destroy, :create]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired 


    if session[:last_order] == "year" 
      @order = "year_desc"
      session[:last_order] = nil
    end
    @active_breweries = case @order
    when 'name' then @active_breweries.sort_by {|b| b.name}
    when 'year' then session[:last_order]= "year"
      @active_breweries.sort_by {|b| b.year}
    when 'year_desc' then session[:last_order] = nil
      @active_breweries.sort_by {|b| -b[:year]} 

    end
    @retired_breweries = case @order
    when 'name' then @retired_breweries.sort_by {|b| b.name}
    when 'year' then session[:last_order]= "year"
      @retired_breweries.sort_by {|b| b.year}
    when 'year_desc' then session[:last_order] = nil
     @retired_breweries.sort_by{|b| -b[:year]}
   end

 end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"#{brewery.name} activity status changed to #{new_status}"
  end
  def nglist
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    private
    def authenticate
     admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}
     authenticate_or_request_with_http_basic do |username, password|
      admin_accounts[username] == password
    end
  end
  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end
   def expire_cache_fragments
     ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
   end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order:"name") %></th>
      <th><%= link_to 'Year', breweries_path(order:"year") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) , class:"btn btn-primary"%></td>
        <td><%= link_to 'Delete', brewery, method: :delete, data: { confirm: "Are you sure you want to delete \'#{brewery.name}\'?" } , class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>
<h2>Active</h2>

<% cache "brewerylist-#{@order}", skip_digest: true do %>


<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<br>
<% end %>

<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-success"%>
</br>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function ($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }

    $scope.searchText = '';
  });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  search:  <input ng-model="searchText">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">Name</a> </th>
    <th> <a ng-click="sort_by('year')">Established</a> </th>
    <th> <a ng-click="sort_by('amount_of_beers')">Beers</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
      <td>{{brewery.amount_of_beers}}</td>
    </tr>
  </table>

</div>

app/views/breweries/show.html.erb
<% cache @brewery do %>
<h2><%= @brewery.name %></h2>
<% if not @brewery.active  %>
<span class="label label-info">retired</span>
<% end %>
<h3><em>Established in <%= @brewery.year%> </em></h3>
<p>Beers in this brewery: <%= @brewery.beers.count%> </p>

<p>
	<% @brewery.beers.each do |beer| %>
	<%= link_to beer.name, beer %></br>
	<% end %>
</p>
<% end %>
<p>
	<% if @brewery.ratings.empty? %>
	No beers in this brewery have been rated
	<% else %>	
	<%= "Has #{pluralize(@brewery.ratings.count, 'rating')}, average #{@brewery.average_rating} " %>
	<% end %>
	
</p>
</br>
<%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<%= edit_and_destroy_buttons(@brewery) %>